const dataSertif ={
"Rafifah" : {message:" SELAMAT SUDAH MENAMATKAN 2025 rafifi, i’m so glad i meet you in this year. Thanks for all the food and places and memories and EVVEEEERYTHING we share. Selamat yah tahun ini sudah menamatkan event-event an mu di teknik, semangat tahun depan pasti akan lebih menyenangkan. Semoga partnerlu bener ya di event event selanjutnya… Semoga harapan-harapan dan rencana-rencana hebat lu terwujud. Semoga juga lu g bosen nungguin gue makan 🤓 I enjoy the moment we had in 2025 so i hope it goes both way. Good luck 2026!!!" , pdf: "assets/images/sertif/Rafifah25.pdf" },
"Aya" : {message:"Congrats for surviving 2025 ayak, i’m so glad i met you in this year anjay. Makasih untuk segala inisiatiflu dalam agenda-agenda sinope dan banyak hal lain. Thanks juga buat jawaban-jawaban unexpected yg keluar dari mulutlu di kala sunyi itu. Semoga 2026 lu lebih happy, semoga lu mau jalan dari kost kek ft, semoga laundry lu ga 11 kg lagi, semoga lu mau masak dan beli dada ayam juga….. Apapun yang baik dan berguna bagi lu dan bangsa ini deh. Good luck 2026 ayakkk." , pdf: "assets/images/sertif/aya25.pdf"},
"Hana" : {message:"Hana dul set, the crazieszszszt girl in town, selamat sudah menamatkan 2025! I’m sooooo glad i met you in this year. Thanks karena sudah hadir dan menghibur dan mengguncang dunia ini han…. Gue ga nyangka ada yg lebih gila dari gue dan ternyata jauhhhh lebih gila dari gue….. Semoga lu happy-happy terus ya. Jadi 2026 masih mau muterin teknik buat nyari sesosok manusia lagi gak hannn? Anywayyyy good luck untuk semua rencana hebat lu di 2026!!!" , pdf:"assets/images/sertif/hana25.pdf" },
"Fairuz" : {message:"FAIRUZIA SAAFFFFF, selamat sudah berhasil melewati 2025. Terima kasih banyak BANGET sudah SANGAT BANYAK membantuku selama IUP applicationku kemaren, IT MEAN A LOT. thanks bby ily so much. Makasih juga sudah mendengarkan cerita aku naksir 81739110 laki-laki (yg serius cuma 2) Makasih juga sudah percaya untuk cerita-cerita tentang AAABIIIGGGHHHHH tp maaf aku ga akan berhenti teriak ABIIIGGHHHHHH it just so satisfying, u shud try HEHEEHEHEHHEHE. SUMPAH TP FIRRR selain i appreciate ramon’s presence so muchhh I APPRECIATE UR PRESENCE MOOOOREEEEE. Makasih yah. Kalo ada apa-apa kontak gw pls serius ini, gue g bilang kaya gini ke semua orang…. I’m rooting for u 🪸 GOOD LUCK 2026!!!" , pdf: "assets/images/sertif/fairuz25.pdf"},
"Bhekti" : {message:"MIR selamat sudah menamatkan 2025. I’m so proud of u. Makasih untuk semua hal baik yang lu lakukan di 2025 kemarin. Gue bangga bgt sama lu. ANJAY. Keren bhek berani mengambil keputusan besar, i know it must be so hard, BUT LOOK AT YOUUUUU, you nailed it anjay GONGGGGG. Semoga lu menikmati semua proses yang perlu dilewati yah. I knowww you’ll doing gREATTTTt. Tenang aja bhek. Aman lah itu. ANYWAYYYY Good luck 2026!!1" , pdf:"assets/images/sertif/Bhekti25.pdf" },
"Naila" : {message:"NAYLAAAAA selamat sudah menamatkan 2025. Makasih yah untuk semua kerja keras kamu di 2025 kemarin. Aku bangga sekali sama kamu. Semoga kamu selalu dikelilingi hal-hal baik dan membahagiakan yahhh. Good luck 2026 sayangku!" , pdf:"assets/images/sertif/naye25.pdf" },
"Sareu" : {message:"MY BABY MY SHAYLAAAA SELAMAT SUDAH MENAMATKAN 2026. I’m sooo proud of u. U’re doing great and amazing SAREUUU. Makasih yah sudah datang menyelamati aku di tekfair kemarin. IT MEAN A LOOOOOT. ILYYYY. Lu kalo ngevent kabarin gue yak. Anywayyyyy makasih yah untuk semua energi dan upaya lu di 2025 kemarin. Good luck 2026!!" , pdf:"assets/images/sertif/Sareu25.pdf" },
"Ayla" : {message:"Aylaaaaahh, Selamat sudah menamatkan 2025!!! Maaf sudah mengguncang hari-harimu dengan perubahan jadwalku. HEHEHE ILY. JGN KAPOOOK. I enjoy our time together BGTTTTT. Semoga lu juga yah. Makasih ya aay untuk segala hal baik yang lu lakukan di 2025 kemarin. I’m SOOOO PROUD OF UUUUUUU. Good luck 2026 ayla my atlet." , pdf: "assets/images/sertif/Ayla25.pdf"},
"Ebo" : {message:"EVANIA BUDOK selamat sudah menamatkan 2025!!! Makasih untuk semua kerja keras kamu di 2025 kemarin yahhhh. You’re getting closer and closer to be a doctor OMG EVAAAA i’m sooo proud of u. Good luck 2026 yah evania " , pdf: "assets/images/sertif/Eva25.pdf"},
"Mayya" : {message:"MAyyyyyyya halooo, selamat sudah menamatkan 2025 dengan baik. I’m so proud of u. Selamat sudah berhasil melalui semua hal yang harus dilalui di 2025 kemarin. Old you will be sooooo proud. Makasih yah sudah mengerahkan energi dan mengupayakan yang terbaik. Makasih udah selalu berbuat baik dan memikirkan orang-orang di sekitar kamu. Kamu pasti kangen pap seksi ku ya mayyy 😁 KWKWKWKW ANYWAYYYY Good luck untuk 2026 sayangg!!" , pdf:"assets/images/sertif/Mayya25.pdf" },
"Kayla" : {message:"ARKEYLA TETEH UNPAD SELAMAT SUDAH MENAMATKAN 2025. Makasih yah sudah mengerahkan energi dan mengupayakan yang terbaik. I’m so proud of u. Semangat belajar jadi dokternya ya arkyela, semoga kamu selalu dikelilingi hal-hal baik. I know u did very great and you’ll be a great doctor sooon. Good luck 2026 arkeyla toba lake." , pdf:"assets/images/sertif/Kayla25.pdf" },
"karina" : {message:"Karinul, it’s finally that time of the year, Selamat sudah menamatkan 2025. WE DEF LEARN A LOT THIS YEARRRR. I’m so proud of u loh. Makasih yah untuk semua usaha dan optimisme kamu itu. Makasih juga udh selalu percaya untuk menceritakan keluh kesahmu tentang satria baja hitam itu. Semoga lu berdua saling membahagiakan terus ya…. I miss flamboyan, we shud go there. gila ya ga pernah ke sana lagi. Anywayyyy Good luck untuk 2026 dokk, pasti kamu akan semakin dokter dan semakin gigi dan semakin bio." , pdf:"assets/images/sertif/Karin25.pdf" },
"Mandi" : {message:"MAMANNNN Congrats for surviving 2025. I’m so proud of uuuuu. Makasih ya untuk semua energi dan kerja keras yang kamu kerahkan di 2025 kemarinn. EH LU TUH blm bisa nyetir lho kalo belum jemput gue ke giwangannnn 😪 Semoga lu selalu dikelilingi hal-hal baik dan membahagiakan ya man. GOOD LUCKKKK UNTUK SEMUA RENCANA HEBAT LU DI 2026. I’m rooting for u alwaysss 🪂" , pdf:"assets/images/sertif/Mandi25.pdf"},
"Akak" : {message:"Pertama, udh main nonchalant-nonchalant nya, kedua, kayanya ini saatnya gue teriak nala kalo gue ketemu lu di FT, ketiga, baru, SELAMAT SUDAH MENAMATKAN 2025 AKAKKKKK! HEHEHEH selamat sudah menamtkan segala jenis hal yg harus dilalui di 2025 kemaren. Aku bangga sekali sama kamu 🐠 Lu merasa UTBK tuh 2025 po? rasanya kaya udah lama banget gasih WKWKWKKWKW. U’re doing sooooo great akak. Makasih yah untuk semua upaya dan kerja keras yang kamu lakukan di 2025 kemaren. Mungkin 2026 saatnya berupaya untuk jadi chalant? Anyway GOOD LUCK 2026!! SELAMAT BEKERJA BERSAMA NALA FAVORITMU ITUUUUUU" , pdf:"assets/images/sertif/Akak25.pdf" },
"Tisya" : {message:"TISYA, the one who always got bad signal EVERYTIME i tell smth important 😑selamat sudah menamatkan 2025 sayangku. YOU DID GREAT, ME SO PROUD OF UUUUU. Walaupun sekarang kita berjarak JAUH tp kamu ttp harus mendengar segala cerita tentang laki-laki yang menarik perhatianku. WLE. I have smth that i haven’t tell u HAHAHAAHAHAHH yah nanti adalah waktunya. Makasih yah sudah selalu mau (gatau sih) mendengarkan, I’m all ear kalo kamu mau bercerita lohhh. OIYA makasih untuk semua energi baik dan kerja keras kamu di 2025 kemarin. Semoga 2026 kamu dipenuhi hal-hal yang membahagiakan 🪷 GGOODD LUCKKK" , pdf: "assets/images/sertif/Tisya25.pdf"},
"Bella" : {message:"Bella sayanggg selamat sudah menamatkan 2025!!!! Makasih ya untuk semua kerja keras kamu di 2025 kemarinnn. I’m so proud of u. Semangat OLGENASSSSS. Semoga kamu selalu dikelilingi hal-hal baik dan membahagiakan yahhhh. Good luck 2026 Bellllalaalalala" , pdf:"assets/images/sertif/Bella25.pdf" }
};

const name = localStorage.getItem("user")
const data = dataSertif[name]

document.getElementById("greeting").textContent = "Hi, " + name + "!";
document.getElementById("message").textContent = data.message;

document.getElementById("certificate").src = data.pdf;

const unduh = document.getElementById("unduh");
unduh.addEventListener("click", () => {
  const link = document.createElement("a");
  link.href = data.pdf;
  link.download = `${name}-SAT25.pdf`; // nama file ketika didownload
  link.click();
});